### ISSUE TITLE
请问会更新2023年的PPT及代码吗？

### ISSUE THREAD

**Issue by Kyson119** [Shao-Kui/D3.js-Demos#11]
本人目前正在学习发布于b站的2023年的课程视频，发现2023年新增的内容（如d3.drag()）并未发布于该仓库内，希望能够更新。

**Comment by Shao-Kui** [comment]
https://cg.cs.tsinghua.edu.cn/course/vis/d3code.html

您好，如果有后续的代码更新，都会在课程主页。这个代码库不更新了。（主要是我不当助教了）
