### ISSUE TITLE
求22年示例代码

### ISSUE THREAD

**Issue by GeroRoman** [Shao-Kui/D3.js-Demos#12]
![image](https://github.com/user-attachments/assets/b63f7644-9a75-4be4-a4f9-5458249cd67e)
您好，非常抱歉打扰到您。我想请问一下这个在课上讲过的示例有没有源码，我想学习一下代码的细节，自己没有复现出来。

**Comment by Shao-Kui** [comment]
https://cg.cs.tsinghua.edu.cn/course/vis/d3code.html

您好，这些代码都在课程主页。不过实验室搬家，服务器暂时挂掉了...请您之后关注一下~谢谢！
