### ISSUE TITLE
导入本地py文件main_hw失败

### ISSUE THREAD

**Issue by xddzb** [Shao-Kui/D3.js-Demos#4]

**Comment by Shao-Kui** [comment]
诶？已经close了么？

内个讲道理不应该啊...如果没解决的话，可以贴下具体报的错哈。

**Comment by xddzb** [comment]
助教老师好，我已经能解决问题啦，感谢

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"小魁少爷"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月22日(星期三) 下午2:00
收件人:&nbsp;"Shao-Kui/D3.js-Demos"<D3.js-Demos@noreply.github.com&gt;;
抄送:&nbsp;"菜菜博"<1741383835@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Shao-Kui/D3.js-Demos] 导入本地py文件main_hw失败 (#4)





 
诶？已经close了么？
 
内个讲道理不应该啊...如果没解决的话，可以贴下具体报的错哈。
